name: ESLint CI
on: push
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn install
      - uses: sibiraj-s/action-eslint@v1.1.0
        with:
          eslintArgs: "--ignore-path=.eslintignore"
          extensions: "js"
          annotations: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
